### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by ProHyphonzDaCoder** [TajuModding/Discord-v13-Button-Tickets-bot#2]
/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355
    const Moder = message.mentions.roles.second() || message.guild.roles.cache.get(args[1]);
                                         ^

TypeError: message.mentions.roles.second is not a function
    at Client.<anonymous> (/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355:42)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Discord-Button-Tickets-Bot@1.0.0 start: `node .`
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
Made by Tejas Lamba#1924
Credits  | Visa2Code | https://discord.gg/vRQtfrAPJ3
Join Above for Support!
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
Web Server Started
Token Working
Logging in to bot...
Logged into Hyphonz Tickets
/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355
    const Moder = message.mentions.roles.second() || message.guild.roles.cache.get(args[1]);
                                         ^

TypeError: message.mentions.roles.second is not a function
    at Client.<anonymous> (/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355:42)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Discord-Button-Tickets-Bot@1.0.0 start: `node .`
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
Made by Tejas Lamba#1924
Credits  | Visa2Code | https://discord.gg/vRQtfrAPJ3
Join Above for Support!
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
Web Server Started
Token Working
Logging in to bot...
Logged into Hyphonz Tickets
/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355
    const Moder = message.mentions.roles.second() || message.guild.roles.cache.get(args[1]);
                                         ^

TypeError: message.mentions.roles.second is not a function
    at Client.<anonymous> (/home/runner/Discord-v13-Button-Tickets-bot-1/index.js:355:42)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/runner/Discord-v13-Button-Tickets-bot-1/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Discord-Button-Tickets-Bot@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Discord-Button-Tickets-Bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-17T22_14_07_480Z-debug.log
exit status 1

**Comment by TajuModding** [comment]
Join server for help 
https://discord.gg/vRQtfrAPJ3
